alwaysrecruit
ggomabbang/dongarimart pull request #68
Opened 2024-09-03 13:50 UTC by taekoong

# ⚠️ 연관된 이슈

> close #60 

# 🔨 작업 내용

> 도메인: 관련 URL(Frontend), API 주소(BackEnd), Schema 등

### 도메인: `/recruit`, '/club\[id]', 'my\recruit/[id]'
- 모집공고 등록 시 상시모집 버튼 생성 ; 상시모집 버튼을 누르면 날짜 선택 기능이 없어지며 모집시작일은 등록일, 모집종료일은 9999-12-31으로 뜬다. 
-  모집공고 수정 시 상시모집 
- 동아리 찾기 및 자세히 보기에서 상시모집 중인 동아리면 모집 기간에 상시모집이라고 뜬다.

# 🖼️ 참고 이미지 및 영상

> (선택)

# 💬 추가 사항

> 개발한 기능이 아닌 추가적으로 전달하고 싶은 말

수정 시 상시모집이면 화면에 체크박스가 표시된 상태로 만들고 싶었는데 실패...해서 일단 현 상황까지만 냅니다.

2024-09-04 01:52 UTC, kyoutae1234 approved these changes

2024-09-04 01:56 UTC, kyoutae1234 requested changes
PR 머지 시 실제 서비스에 바로 반영되기 때문에, 완성 후 PR 제출해주시기 바랍니다

2024-09-09 12:00 UTC, bluelemon61 approved these changes
ㅊㅊㅊㅊㅊㅊ

2024-09-09 12:02 UTC, kyoutae1234 approved these changes

2024-09-09 12:02 UTC, merged